name: Test on push
on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: 'Test: ${{ matrix.os }} (node@${{ matrix.NODE_VERSION }})'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        OS: [ubuntu-latest, macos-latest, windows-latest]
        NODE_VERSION: [18, 20]
      fail-fast: false
    env:
      NODE_VERSION: ${{ matrix.NODE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node@${{ matrix.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NODE_VERSION }}

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
